application: weblaputa
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /.*
  script: server.app
